on:
  release:
    types: [published]

name: Deploy

jobs:
  deploy:
    name: Build and deploy to GAE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
        run: npm install
        run: npm build
      - name: Deploy to GAE
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
